### ISSUE TITLE
Bug after fimap updated

### ISSUE THREAD

**Issue by GoogleCodeExporter** [kurobeats/fimap#63]
```
Which version of fimap you are using? (You can see that in the very first line)
fimap v.09_svn (For the Swarm)

On what operating system?
Fedora release 8 (Werewolf)

Please provide any additional information below.
./fimap.py -g -q 'inurl:lista.php"'
Traceback (most recent call last):
  File "./fimap.py", line 29, in <module>
    from bingScan import bingScan
  File "/home/carlitos/fimap/src/bingScan.py", line 23, in <module>
    from pybing import Bing
ImportError: No module named pybing


```

Original issue reported on code.google.com by `cmendoza...@gmail.com` on 17 Nov 2011 at 8:45

**Comment by BenMoore71** [comment]
Same stuff, did it got fixed?
