### ISSUE TITLE
error bing scan and httplib2

### ISSUE THREAD

**Issue by amudy17** [kurobeats/fimap#83]
ubuntu@ip-172-31-53-178:~/fimap-master/src$ ./fimap.py -h
Traceback (most recent call last):
  File "./fimap.py", line 29, in <module>
    from bingScan import bingScan
  File "/home/ubuntu/fimap-master/src/bingScan.py", line 23, in <module>
    from pybing import Bing
  File "/home/ubuntu/fimap-master/src/pybing/__init__.py", line 9, in <module>
    from bing import Bing
  File "/home/ubuntu/fimap-master/src/pybing/bing.py", line 14, in <module>
    import urllib, httplib2
ImportError: No module named httplib2

**Comment by LynXcode** [comment]
ImportError: No module named # httplib2 install this python module and run again.
